services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MYSQL_DATABASE: YOUR_DATABASE
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://YOUR_USERNAME:YOUR_PASSWORD@db:3306/YOUR_DATABASE
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data:
